show databases;
use course;
show tables;
select *from students;
select *from students where gpa=2.5;
select *from students where gender="f";
select std_name,sid from students where gender="f";
select *from students where gpa<2.5;
select std_name from students where gpa<2.5;
select *from students where gpa>2.5;
select *from students where gpa<=2.5;
select *from students where gpa>=2.5;
select *from students where gpa !=2.5;
select *from students where gpa <>2.5;
select *from students where gpa=2.5 and gender="f";
select *from students where gpa<2.5 and gender="m";
select *from students where gpa<2.5 and age<25 and gender="m";
select *from students where gpa>2.5 or gender="f";
select *from students where gpa<2.5 or age=24 or gender="m";
select *from students where gpa<2.5 and age=24 or gender="f";
select *from students where not age=25;
select *from students where not gpa=2.4;
select *from students where gpa<2.4 and age>24 and not gender="f";
select std_name from students where gpa<=2.5 and not age=25
and gender="m";
select *from students where gpa between 2.3 and 2.5;
select *from students where age between 24 and 26;
select std_name,gender from students where gpa between 2.4 and 2.6;
select *from students where gpa not between 2.3 and 2.5;
select sid,dob from students where age not between 23 and 25;
select *from students where gpa in(2.1,2.3,2.5,2.7);
select *from students where age in(23,25);
select *from students where age in(22,24) and gender="m";
select *from students where gpa not in(2.3,2.5);
select *from students where age not in(23,25) and gender="f";